# This is a basic workflow to help you get started with Actions
---
name: Deploy Website With Surge
on:
  push:
    branches:
      -master
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    name: Job_Deploy_Surge
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Node Setup
      uses: actions/checkout@v2-beta
      with:
        node_version: '12'
      - name: setup surge
        run: npm install --global surge
      - name: deployment with surge
        run: surge ./ bootcamp_setup.surge.sh --token ${{ secrets.PROJECT001_SURGE_TOKEN }}

    
